services:
  sub-proxy-updater:
    image: ghcr.io/wanglz111/sub-proxy-updater:latest
    container_name: sub-proxy-updater
    restart: unless-stopped
    env_file:
      - .env
    environment:
      UPDATE_INTERVAL_SECONDS: ${UPDATE_INTERVAL_SECONDS:-1800}
